
#@url = http://localhost:7777
@url = https://selfpromo-back.herokuapp.com

### echo
GET {{url}}/echo
Content-Type: application/json

### sqlite test crap
GET {{url}}/test_crap
Content-Type: application/json

### articles GET
GET {{url}}/articles
Content-Type: application/json

### articles by ID GET
GET {{url}}/articles/2
Content-Type: application/json

### reviews GET
GET {{url}}/reviews
Content-Type: application/json
